name: myenv
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - missingno
  - pytorch
  - pytorch-cuda=12.4
  - pyyaml
  - scikit-learn
  - kaggle
  - rdkit
  - pytest
