# Use AlmaLinux 9 image
FROM almalinux:9

# Install dependence
RUN dnf -y update && dnf -y install \
#    curl \
    git \
    sudo \
    bzip2 \
    && dnf clean all

# Install Miniconda
RUN curl -fsSL https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/miniconda.sh \
    && bash /tmp/miniconda.sh -b -p /opt/miniconda \
    && rm /tmp/miniconda.sh

# Update conda
RUN /opt/miniconda/bin/conda update -y conda

# Set work directory
WORKDIR /app/CI_Test

# Copy the github repo to the docker container
COPY . /app/CI_Test/.

# Use environment.yml to build the Conda environment
RUN /opt/miniconda/bin/conda env create -f environment.yml

# Set PATH to let Conda and my module available in the docker container
ENV PATH /opt/miniconda/envs/myenv/bin:$PATH
ENV PYTHONPATH /app:$PYTHONPATH

# Execute pytest
CMD ["/opt/miniconda/envs/myenv/bin/pytest"]
