name: code-syntax-test

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true
  
jobs:
  code-syntax-test:
    runs-on: self-hosted

    #services:
    #  docker:
      
    #    image: docker:19.03.12
    #    options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    #- name: Set up Docker Buildx
    #  uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -f Dockerfiles/Dockerfile.code-syntax-test -t my-docker-image .
        
