name: Test with Docker and Miniconda

on:
  pull_request:
    branches:
      - main


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  code-syntax-test:
    runs-on: self-hosted

    #services:
      # Docker 服務配置，確保 Docker 運行
    #  docker:
      
    #    image: docker:19.03.12
    #    options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    #- name: Set up Docker Buildx
    #  uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -f Dockerfiles/Dockerfile.code-syntax-test -t my-docker-image .


  run-tests:
    runs-on: self-hosted
    needs: code-syntax-test

    #services:
      # Docker 服務配置，確保 Docker 運行
    #  docker:
    #    image: docker:19.03.12
    #    options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    #- name: Set up Docker Buildx
    #  uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -f Dockerfiles/Dockerfile.run-tests -t my-docker-image .

    - name: Run pytest in Docker
      run: |
        docker run --rm my-docker-image

    - name: Run pytest in Docker
      run: |
        docker run --rm my-docker-image

  cleanup:
    if: ${{ always() }}
    runs-on: self-hosted
    needs: run-tests
    steps:
      - name: Cleanup docker
        run: |
          docker container prune -f
          docker volume prune -f
          docker image prune -f
          docker builder prune -f

