name: Test with Docker and Miniconda

on:
  pull_request:
    branches:
      - main
      
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  code-syntax-test:
    runs-on: self-hosted

    services:
      # Docker 服務配置，確保 Docker 運行
      docker:
      
        image: docker:19.03.12
        options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    #- name: Set up Docker Buildx
    #  uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -f Dockerfiles/Dockerfile.code-syntax-test -t my-docker-image .


  run-tests:
    runs-on: self-hosted
    needs: code-syntax-test

    services:
      # Docker 服務配置，確保 Docker 運行
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    #- name: Set up Docker Buildx
    #  uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -f Dockerfiles/Dockerfile.run-tests -t my-docker-image .

    - name: Run pytest in Docker
      run: |
        docker run --rm my-docker-image

    - name: Run pytest in Docker
      run: |
        docker run --rm my-docker-image

    - name: Post summary to PR
      if: github.event_name == 'pull_request'
      uses: peter-evans/create-or-update-comment@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          :white_check_mark: Test was finished:
          
          - Test package：pytest
          - Status：${{ steps.check_status.outputs.status == 'passed' && ':white_check_mark: Test is successful ! ' || ':x: Test is Failed !' }}
          - Commit：`${{ github.sha }}`
          - Branch：`${{ github.head_ref }}`

