name: Test with Docker and Miniconda

on:

  pull_request:
    branches:
      - main

jobs:
  env-setup-test:
    runs-on: self-hosted

    

    #services:
      # Docker 服務配置，確保 Docker 運行
    #  docker:
    #    image: docker:19.03.12
    #    options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    #- name: Set up Docker Buildx
    #  uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -f Dockerfiles/Dockerfile.code-syntax-test -t my-docker-image .

    - name: Run pytest in Docker
      run: |
        docker run --rm my-docker-image

